version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # 👈 Подключаем папку с проектом внутрь контейнера
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  volumes:
    caddy_data:
    caddy_config: